### ISSUE TITLE
va.gov email addresses in use

### ISSUE THREAD

**Issue by pwideman** [department-of-veterans-affairs/appeals-consumer#203]
As per our [announcement](https://github.com/orgs/department-of-veterans-affairs/discussions/13), you are receiving this notification because there is activity in this repository that violates a forthcoming repository ruleset to prevent va.gov email addresses leaking through commit metadata in public VA repositories.

These users have activity since Nov 14 that is in violation of this policy:

@raymond-hughes 

If the users have since updated their email settings then this notification can be safely ignored.

@department-of-veterans-affairs/caseflow-tech-leads

**Comment by raymond-hughes** [comment]
This is resolved
